# =========================
# Kitty - Main Config
# =========================

# ---------- Fonts ----------
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# ---------- Window ----------
remember_window_size yes
window_padding_width 10
confirm_os_window_close 0
placement_strategy center

# ---------- Transparency ----------
background_opacity 0.92
dynamic_background_opacity yes

# ---------- Mouse / URLs ----------
mouse_hide_wait 1.5
detect_urls yes
open_url_with default

# ---------- Bell ----------
enable_audio_bell no
visual_bell_duration 0.0

# ---------- Scrollback ----------
scrollback_lines 10000

# ---------- Scrollbar ----------
scrollbar never

# ---------- Tabs ----------
tab_bar_style fade
tab_fade 0.20 0.45 0.75 1
tab_activity_symbol "•"
tab_title_max_length 24

# ---------- Cursor ----------
shell_integration no-cursor
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0.7 ease-in-out
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.08 0.22
cursor_trail_start_threshold 1
cursor_trail_color none

# ---------- Active theme ----------
include current-theme.conf