# =========================
# Kitty - Gruvbox Modern
# =========================


# ---------- Fonts ----------
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# ---------- Window ----------
remember_window_size yes
window_padding_width 10
confirm_os_window_close 0
placement_strategy center

# ---------- Transparency ----------
background_opacity 0.92
dynamic_background_opacity yes

# ---------- Mouse / URLs ----------
mouse_hide_wait 1.5
detect_urls yes
url_color #83a598
url_style curly
open_url_with default

# ---------- Bell ----------
enable_audio_bell no
visual_bell_duration 0.0

# ---------- Scrollback ----------
scrollback_lines 10000

# ---------- Scrollbar ----------
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.6
scrollbar_hover_width 1.0
scrollbar_handle_opacity 0.70
scrollbar_radius 0.25
scrollbar_gap 0.12
scrollbar_min_handle_height 1.2
scrollbar_hitbox_expansion 0.20
scrollbar_handle_color #a89984
scrollbar_track_color #3c3836
scrollbar never
# ---------- Tabs ----------
tab_bar_style fade
tab_fade 0.20 0.45 0.75 1
tab_activity_symbol "•"
tab_title_max_length 24

active_tab_foreground   #282828
active_tab_background   #b8bb26
active_tab_font_style   bold

inactive_tab_foreground #a89984
inactive_tab_background #3c3836
inactive_tab_font_style normal

tab_bar_background #1d2021
tab_bar_margin_color #1d2021

# ---------- Selection ----------
selection_foreground #282828
selection_background #ebdbb2

# ---------- Main Gruvbox Colors ----------
foreground #ebdbb2
background #282828

cursor     #ebdbb2

# ---------- ANSI Color Table ----------
color0  #282828
color1  #cc241d
color2  #b8bb26
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984

color8  #928374
color9  #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2

# Block cursor
shell_integration no-cursor
cursor_shape block
cursor_shape_unfocused hollow

# Cursor colors
cursor #ebdbb2
cursor_text_color background

# Blink animation
cursor_blink_interval 0.7 ease-in-out
cursor_stop_blinking_after 0

# Movement trail animation
cursor_trail 1
cursor_trail_decay 0.08 0.22
cursor_trail_start_threshold 1
cursor_trail_color none
